<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- framework -->
    <TargetFramework>net9.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
    <NoWarn>NU1900</NoWarn>

    <!-- compiler -->
    <LangVersion>latest</LangVersion>
    <DebugSymbols>false</DebugSymbols>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>

    <!-- language -->
    <Nullable>enable</Nullable>
    <RootNamespace/>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="NUnit" Version="4.2.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageReference Include="OkTools.Core" Version="1.0.19" />
    <PackageReference Include="Shouldly" Version="4.2.1" />
  </ItemGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <ItemGroup>
      <AssemblyAttributes Include="InputLocationAttribute">
        <_Parameter1>$(ProjectDir)aoc</_Parameter1>
      </AssemblyAttributes>
    </ItemGroup>
    <WriteCodeFragment
      AssemblyAttributes="@(AssemblyAttributes)" Language="C#"
      OutputDirectory="$(IntermediateOutputPath)" OutputFile="BuildProperties.cs">
      <Output TaskParameter="OutputFile" ItemName="Compile" />
      <Output TaskParameter="OutputFile" ItemName="FileWrites" />
    </WriteCodeFragment>
  </Target>

</Project>
